### PR TITLE
sites.yml: add blog.leenucks.xyz

### PR DESCRIPTION
**Pull request by yusi1**
Website (if applicable): https://blog.leenucks.xyz
This PR is:

- [X] Adding a new domain
- [ ] Updating existing domain
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (darktheme.club site)
- [ ] Other not listed

- [X] The following information is filled identical to the data file

***I confirm that I have read the [FAQ page](https://darktheme.club/faq), particularly the red section about inappropriate content, and I attest that this site is appropriate based on those criteria.***

- [X] Check to confirm

```
- domain: blog.leenucks.xyz
  url: https://blog.leenucks.xyz/ (Make sure you keep the trailing slash)
  method: darkonly
  last_checked: 2024-11-14
```

### CODE REVIEW

**Comment by yusi1** [comment]
Screenshot_2024-11-17_20-23-12

proof of darkmode

**Comment by garritfra** [comment]
Hi, thanks for adding your site. It's currently unreachable for me?

**Comment by yusi1** [comment]
> Hi, thanks for adding your site. It's currently unreachable for me?

ah sorry should be up now.

**Comment by garritfra** [comment]
LGTM 🙂 Thanks!

**Pull request merged**
