### PR TITLE
Add nebula.app

### PR DESCRIPTION
**Pull request by realpixelcode**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (darktheme.club site)
- [ ] Other not listed

- [x] The domain is in the correct alphabetical order
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://darktheme.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: nebula.app
  url: https://nebula.app/
  method: javascript
  last_checked: 2022-07-16
```

### CODE REVIEW

**Comment by garritfra** [comment]
This site is light mode by default.🙈

**Comment by realpixelcode** [comment]
> This site is light mode by default.see_no_evil

Oh, you need to be logged in for dark mode to apply, I think. In the profile settings, you can choose between device theme (default), light and dark. (Since Nebula is a paid video platform, it doesn't really make much sense to visit it without an account anyway.)

**Comment by garritfra** [comment]
> > This site is light mode by default.see_no_evil
> 
> Oh, you need to be logged in for dark mode to apply, I think. In the profile settings, you can choose between device theme (default), light and dark. (Since Nebula is a paid video platform, it doesn't really make much sense to visit it without an account anyway.) 

My idea of the site is that, when someone browses the list, he will discover pages that use a dark theme. If he has to log in, that kind of defeats this explorative spirit.

**Comment by realpixelcode** [comment]
Fair enough. 😅

**Pull request closed without merging**
